### ISSUE TITLE
Spawning Julia process fails

### ISSUE THREAD

**Issue by StefanMathis** [aminya/CompileBot.jl#43]
Hello, 

I set up the CompileBot as described for a local (non-GitHub) package on Windows 10:

```julia
using CompileBot

snoop_bot(BotConfig("MyPackage"))
```

However, when running this file, I get the following error:
```julia
LoadError: IOError: could not spawn `julia --code-coverage=none --project=@. -e "
```

Any idea on what goes wrong here?

**Comment by aminya** [comment]
What Julia version are you on? Is Julia on the PATH?

**Comment by StefanMathis** [comment]
Thanks for the fast reply. You identified the error: Julia was not on my systems path. Once it was addet, the CompileBot works perfectly :-)

For anyone who finds this thread: The solution is to add Julia to the system PATH as described here:
https://julialang.org/downloads/platform/

@aminya: I think it would be a good idea to add a hint to the documentation. When I find some time during the weekend, I'll issue a corresponding PR.

**Comment by aminya** [comment]
Feel free to open a pull request for adding this to the docs
